use_frameworks!

platform :ios, '8.0'

target 'zpodpod_Example' do
  pod 'zpodpod', :path => '../'

  target 'zpodpod_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
